name: Deploy to S3

on:
  push:
    branches:
      - main  # Só faz deploy quando a branch main for atualizada

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Altere se seu bucket estiver em outra região

      - name: Fazer deploy para o S3
        run: aws s3 sync ./site s3://meu-site-estatico-bucket --delete
